export enum ELoginType {
    AUTHENTICATE_USER = 'AUTHENTICATE_USER',
    GETOAUTH_USERS = 'GETOAUTH_USERS',
    GET_ALL_POST = 'GET_ALL_POST',
    GET_POST = 'GET_POST',
    DELETE_POST = 'DELETE_POST',
    LOGOUT_USER = 'LOGOUT_USER'
}
